# play level at variables
- name: play level  variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
      - name: print URL
        ansible.builtin.debug:
          msg: rama-{{ URL }}

  # Demo on task level