# play level at variables
- name: play level  variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
      - name: print URL
        ansible.builtin.debug:
          msg: rama-{{ URL }}

  # Demo on task level
  # only that task have that variable, other tasks cannot access it.
- name: task level  variables
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: rama-{{ URL }}
      vars:
        URL: taskexample.com

# Load var from file

- name: load variable from file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: rama-{{ URL}}
# vars_file does not support task level, it is for play level only.

# var from roles

- name: variable from roles
  hosts: all
  vars:
    URL: role.example.com    #  i have written for successful execution
    URL_PLAY: play.example.com
  roles:
    - sample

- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell: uptime




