# play level at variables
- name: play level  variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
      - name: print URL
        ansible.builtin.debug:
          msg: rama-{{ URL }}

  # Demo on task level
- name: task level  variables
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: rama-{{ URL }}
      vars:
        URL: taskexample.com

# Load var from file

- name: load variable from file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: rama-{{ URL}}

# var from roles

- name: load variable from roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample



